FROM python:latest

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y --no-install-recommends ffmpeg

COPY ./ ./

RUN pip install -r requirements.txt

CMD python app.py & python handler.py
